M48
; DRILL file {KiCad (6.0.2)} date Thu Aug 25 15:18:45 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-25T15:18:45+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
%
G90
G05
T1
X5.053Y-5.4202
X5.2806Y-5.4202
X5.8109Y-5.4202
X6.0385Y-5.4202
T0
M30
